uvicorn.error - INFO - Started server process [8443]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 11:48:35,299 - Started server process [8635]
2020-11-09 11:48:35,299 - Waiting for application startup.
2020-11-09 11:48:35,300 - Application startup complete.
2020-11-09 11:48:35,301 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 11:49:33,239 - File with name c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65 was not found
2020-11-09 11:51:28,671 - Started server process [8861]
2020-11-09 11:51:28,672 - Waiting for application startup.
2020-11-09 11:51:28,674 - Application startup complete.
2020-11-09 11:51:28,675 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 11:51:33,616 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 56, in upload
    async with AIOFile(f'bin_for_temp_vids/{name}.mp4', 'ab') as file:
NameError: name 'name' is not defined
2020-11-09 11:51:54,993 - Started server process [8912]
2020-11-09 11:51:54,994 - Waiting for application startup.
2020-11-09 11:51:54,995 - Application startup complete.
2020-11-09 11:51:54,996 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 11:51:57,822 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    logging(f'Writing in the {file_name}')
TypeError: 'module' object is not callable
2020-11-09 11:52:27,509 - Started server process [8974]
2020-11-09 11:52:27,510 - Waiting for application startup.
2020-11-09 11:52:27,511 - Application startup complete.
2020-11-09 11:52:27,512 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 11:53:38,439 - Started server process [9066]
2020-11-09 11:53:38,440 - Waiting for application startup.
2020-11-09 11:53:38,441 - Application startup complete.
2020-11-09 11:53:38,442 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 11:55:43,257 - Started server process [9271]
2020-11-09 11:55:43,257 - Waiting for application startup.
2020-11-09 11:55:43,258 - Application startup complete.
2020-11-09 11:55:43,259 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 11:55:47,694 - Deleting file
2020-11-09 11:56:15,761 - Started server process [9330]
2020-11-09 11:56:15,762 - Waiting for application startup.
2020-11-09 11:56:15,763 - Application startup complete.
2020-11-09 11:56:15,764 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 11:56:17,393 - Deleting file: c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 11:57:10,073 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 11:57:14,545 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 11:57:16,380 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 12:02:58,672 - Started server process [11629]
2020-11-09 12:02:58,673 - Waiting for application startup.
2020-11-09 12:02:58,674 - Application startup complete.
2020-11-09 12:02:58,675 - [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
2020-11-09 12:02:58,676 - Waiting for application shutdown.
2020-11-09 12:02:58,676 - Application shutdown complete.
2020-11-09 12:03:10,261 - Started server process [11668]
2020-11-09 12:03:10,262 - Waiting for application startup.
2020-11-09 12:03:10,264 - Application startup complete.
2020-11-09 12:03:10,265 - [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
2020-11-09 12:03:10,265 - Waiting for application shutdown.
2020-11-09 12:03:10,265 - Application shutdown complete.
2020-11-09 12:05:15,482 - Started server process [11811]
2020-11-09 12:05:15,483 - Waiting for application startup.
2020-11-09 12:05:15,484 - Application startup complete.
2020-11-09 12:05:15,485 - [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
2020-11-09 12:05:15,485 - Waiting for application shutdown.
2020-11-09 12:05:15,485 - Application shutdown complete.
2020-11-09 12:06:28,708 - Started server process [11986]
2020-11-09 12:06:28,709 - Waiting for application startup.
2020-11-09 12:06:28,710 - Application startup complete.
2020-11-09 12:06:28,711 - [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
2020-11-09 12:06:28,711 - Waiting for application shutdown.
2020-11-09 12:06:28,712 - Application shutdown complete.
2020-11-09 12:07:14,884 - Started server process [12166]
2020-11-09 12:07:14,885 - Waiting for application startup.
2020-11-09 12:07:14,886 - Application startup complete.
2020-11-09 12:07:14,887 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 12:08:16,542 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 12:08:21,494 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 12:08:47,118 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 12:09:24,446 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 12:10:55,150 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 12:11:33,265 - Writing in the c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-09 12:15:54,003 - Was created dd991230-6c22-4ab3-9ce8-ff02e27c0121
2020-11-09 12:16:13,231 - Writing in the dd991230-6c22-4ab3-9ce8-ff02e27c0121
2020-11-09 12:16:19,196 - Writing in the dd991230-6c22-4ab3-9ce8-ff02e27c0121
2020-11-09 12:16:25,288 - Writing in the dd991230-6c22-4ab3-9ce8-ff02e27c0121
2020-11-09 12:20:27,372 - Started server process [14224]
2020-11-09 12:20:27,372 - Waiting for application startup.
2020-11-09 12:20:27,373 - Application startup complete.
2020-11-09 12:20:27,374 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 12:21:06,700 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:21:07,725 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:21:22,142 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:21:23,618 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:21:30,308 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:21:40,664 - Started server process [14416]
2020-11-09 12:21:40,665 - Waiting for application startup.
2020-11-09 12:21:40,666 - Application startup complete.
2020-11-09 12:21:40,668 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 12:21:46,020 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:21:50,904 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:22:12,483 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:22:32,434 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 58, in upload
    await afp.fsync()
NameError: name 'afp' is not defined
2020-11-09 12:23:21,874 - Started server process [14682]
2020-11-09 12:23:21,875 - Waiting for application startup.
2020-11-09 12:23:21,876 - Application startup complete.
2020-11-09 12:23:21,877 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 12:23:24,451 - Writing in the dd991230-6c22-4ab3-9ce8-ff02e27c0121
2020-11-09 12:23:47,553 - Was created 55e029ca-a47d-440f-a6ba-6cae68fcd44e
2020-11-09 12:24:04,236 - Writing in the 55e029ca-a47d-440f-a6ba-6cae68fcd44e
2020-11-09 12:24:09,839 - Writing in the 55e029ca-a47d-440f-a6ba-6cae68fcd44e
2020-11-09 12:24:13,900 - Writing in the 55e029ca-a47d-440f-a6ba-6cae68fcd44e
2020-11-09 12:27:24,663 - Started server process [15212]
2020-11-09 12:27:24,664 - Waiting for application startup.
2020-11-09 12:27:24,665 - Application startup complete.
2020-11-09 12:27:24,666 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 20:06:14,694 - Started server process [4164]
2020-11-09 20:06:14,695 - Waiting for application startup.
2020-11-09 20:06:14,696 - Application startup complete.
2020-11-09 20:06:14,697 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-09 20:07:45,659 - Deleted file: dd991230-6c22-4ab3-9ce8-ff02e27c0121
2020-11-09 20:07:45,659 - Error while deleting dd991230-6c22-4ab3-9ce8-ff02e27c0121 err: module 'starlette.status' has no attribute 'HTTP_200_INTERNAL_SERVER_ERROR'
2020-11-09 20:08:56,594 - Started server process [4778]
2020-11-09 20:08:56,595 - Waiting for application startup.
2020-11-09 20:08:56,596 - Application startup complete.
2020-11-09 20:08:56,597 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 10:26:11,720 - "GET /?state=yZ8KUIgTvJznikIWIItVL9H8FgttIG&code=4/0AY0e-g7RTZXwX-tpLzaOROHCvB4zOJidPlWsL-tW0ruQIniEUYXTcxdK20DfdzgIzdavfg&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-11 10:27:20,912 - "GET /?state=ZpEnOPdqt3ULNadzZcjD1oX60pgq0e&code=4/0AY0e-g6pc45vdFZARsvb2Vu0aE_uiJPtvZSo-CadjQVEXW39k5yU7Dbpqg20jq2PudN-FQ&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-11 10:46:03,855 - Started server process [7939]
2020-11-11 10:46:03,856 - Waiting for application startup.
2020-11-11 10:46:03,857 - Application startup complete.
2020-11-11 10:46:03,860 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 10:47:16,904 - Started server process [8074]
2020-11-11 10:47:16,905 - Waiting for application startup.
2020-11-11 10:47:16,905 - Application startup complete.
2020-11-11 10:47:16,906 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 10:47:18,935 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 89, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id)
  File "/home/sergey/Documents/nvr/video/main.py", line 110, in upload
    async with ClientSession() as session:
NameError: name 'ClientSession' is not defined
2020-11-11 10:48:11,455 - Started server process [8252]
2020-11-11 10:48:11,456 - Waiting for application startup.
2020-11-11 10:48:11,457 - Application startup complete.
2020-11-11 10:48:11,458 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 10:48:20,913 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id)
  File "/home/sergey/Documents/nvr/video/main.py", line 120, in upload
    async with AIOFile(file_path, 'rb') as afp:
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'test1'
2020-11-11 10:51:37,501 - Started server process [8544]
2020-11-11 10:51:37,502 - Waiting for application startup.
2020-11-11 10:51:37,505 - Application startup complete.
2020-11-11 10:51:37,507 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 10:51:46,021 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id)
  File "/home/sergey/Documents/nvr/video/main.py", line 120, in upload
    async with AIOFile(file_path, 'rb') as afp:
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: ''
2020-11-11 10:52:02,657 - Started server process [8627]
2020-11-11 10:52:02,658 - Waiting for application startup.
2020-11-11 10:52:02,659 - Application startup complete.
2020-11-11 10:52:02,660 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 11:00:46,491 - Started server process [9360]
2020-11-11 11:00:46,492 - Waiting for application startup.
2020-11-11 11:00:46,493 - Application startup complete.
2020-11-11 11:00:46,494 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 11:00:54,368 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id, file_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 121, in upload
    async with AIOFile(file_path, 'rb') as afp:
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '55e029ca-a47d-440f-a6ba-6cae68fcd44e'
2020-11-11 11:01:43,818 - Started server process [9495]
2020-11-11 11:01:43,819 - Waiting for application startup.
2020-11-11 11:01:43,824 - Application startup complete.
2020-11-11 11:01:43,830 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 11:01:52,730 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id, file_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 121, in upload
    async with AIOFile(f'{file_path}.mp4', 'rb') as afp:
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '55e029ca-a47d-440f-a6ba-6cae68fcd44e.mp4'
2020-11-11 11:02:19,653 - Started server process [9600]
2020-11-11 11:02:19,654 - Waiting for application startup.
2020-11-11 11:02:19,657 - Application startup complete.
2020-11-11 11:02:19,665 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 11:02:23,766 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id, file_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 122, in upload
    file_size = str(os.stat(file_path).st_size)
FileNotFoundError: [Errno 2] No such file or directory: '55e029ca-a47d-440f-a6ba-6cae68fcd44e'
2020-11-11 11:03:13,630 - Started server process [9747]
2020-11-11 11:03:13,631 - Waiting for application startup.
2020-11-11 11:03:13,632 - Application startup complete.
2020-11-11 11:03:13,633 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 11:03:17,979 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id, file_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 140, in upload
    logger.info(
NameError: name 'logger' is not defined
2020-11-11 11:36:00,302 - Shutting down
2020-11-11 11:36:00,404 - Waiting for application shutdown.
2020-11-11 11:36:00,405 - Application shutdown complete.
2020-11-11 11:36:00,406 - Finished server process [9747]
2020-11-11 17:45:41,472 - "GET /?state=eHcrxiJ9fWjJ69Hj7w0eky7Vg671He&code=4/0AY0e-g4bwW-PDyb-KZdqD2-mJI4OGdVo1LR3kX1OykdnTzT8IEkKNlX4gza3Nhw5rnt7Xg&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-11 17:45:41,740 - Started server process [3354]
2020-11-11 17:45:41,741 - Waiting for application startup.
2020-11-11 17:45:41,742 - Application startup complete.
2020-11-11 17:45:41,743 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 17:46:52,575 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 96, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id, file_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 134, in upload
    async with session.put(session_url, data=chunk, ssl=False,
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiohttp/client.py", line 411, in _request
    url = URL(str_or_url)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/yarl/_url.py", line 158, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str
2020-11-11 17:48:01,522 - Started server process [4179]
2020-11-11 17:48:01,522 - Waiting for application startup.
2020-11-11 17:48:01,523 - Application startup complete.
2020-11-11 17:48:01,524 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 17:48:43,412 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 96, in declare_stop
    await upload(data_for_google.file_path, data_for_google.id, file_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 145, in upload
    logger.info(
NameError: name 'logger' is not defined
2020-11-11 20:55:23,047 - Started server process [12561]
2020-11-11 20:55:23,048 - Waiting for application startup.
2020-11-11 20:55:23,048 - Application startup complete.
2020-11-11 20:55:23,049 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 20:56:20,392 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 77, in declare_stop
    data_for_google.folder_name, server_file_name)
NameError: name 'server_file_name' is not defined
2020-11-11 20:56:55,575 - Started server process [12783]
2020-11-11 20:56:55,576 - Waiting for application startup.
2020-11-11 20:56:55,577 - Application startup complete.
2020-11-11 20:56:55,578 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 20:58:05,039 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 77, in declare_stop
    data_for_google.folder_name, server_file_name)
NameError: name 'server_file_name' is not defined
2020-11-11 20:58:36,073 - Started server process [12946]
2020-11-11 20:58:36,074 - Waiting for application startup.
2020-11-11 20:58:36,076 - Application startup complete.
2020-11-11 20:58:36,077 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 20:59:47,471 - Started server process [13061]
2020-11-11 20:59:47,472 - Waiting for application startup.
2020-11-11 20:59:47,473 - Application startup complete.
2020-11-11 20:59:47,474 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:00:07,942 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 76, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in upload_to_google
    folder_id = create_folder()
TypeError: create_folder() missing 1 required positional argument: 'folder_name'
2020-11-11 21:00:25,136 - Started server process [13163]
2020-11-11 21:00:25,137 - Waiting for application startup.
2020-11-11 21:00:25,138 - Application startup complete.
2020-11-11 21:00:25,139 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:01:31,748 - Started server process [13271]
2020-11-11 21:01:31,748 - Waiting for application startup.
2020-11-11 21:01:31,748 - Application startup complete.
2020-11-11 21:01:31,749 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:01:34,243 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 76, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in upload_to_google
    folder_id = await create_folder(folder_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 137, in create_folder
    logger.info(
NameError: name 'logger' is not defined
2020-11-11 21:01:49,466 - Started server process [13324]
2020-11-11 21:01:49,466 - Waiting for application startup.
2020-11-11 21:01:49,467 - Application startup complete.
2020-11-11 21:01:49,467 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:01:50,628 - Creating folder with name folder inside folder with id 1weIs_vptfXVN20hSIpN9thL7Vh7VgH3h
2020-11-11 21:01:50,629 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 76, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in upload_to_google
    folder_id = await create_folder(folder_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 149, in create_folder
    headers=HEADERS,
NameError: name 'HEADERS' is not defined
2020-11-11 21:03:13,443 - Started server process [13510]
2020-11-11 21:03:13,444 - Waiting for application startup.
2020-11-11 21:03:13,445 - Application startup complete.
2020-11-11 21:03:13,446 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:03:14,085 - Creating folder with name folder inside folder with id 1weIs_vptfXVN20hSIpN9thL7Vh7VgH3h
2020-11-11 21:03:14,098 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 76, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 91, in upload_to_google
    folder_id = await create_folder(folder_name)
  File "/home/sergey/Documents/nvr/video/main.py", line 145, in create_folder
    headers=HEADERS,
NameError: name 'HEADERS' is not defined
2020-11-11 21:05:32,665 - "GET /?state=NENgSbpPkSdqs5zgGMyINaJeOHVtUS&code=4/0AY0e-g6zbPsS7X2dTlwZunqqtpEPyO9vUSTosqishkmZFPYr9cla0dDEHIkcQVTsXHC9Eg&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-11 21:05:32,933 - Started server process [13883]
2020-11-11 21:05:32,933 - Waiting for application startup.
2020-11-11 21:05:32,934 - Application startup complete.
2020-11-11 21:05:32,935 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:05:38,941 - Creating folder with name folder inside folder with id 1weIs_vptfXVN20hSIpN9thL7Vh7VgH3h
2020-11-11 21:07:23,026 - "GET /?state=8h6MpP69XO6TQilNoNMeHMbbeyhgtH&code=4/0AY0e-g5wVwWhQqlmERMDZW_ychR7uJP8RvxigPewngiiLnCWtoZt1-jZpR5QhYOeZTMUvA&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-11 21:07:23,269 - Started server process [14588]
2020-11-11 21:07:23,270 - Waiting for application startup.
2020-11-11 21:07:23,271 - Application startup complete.
2020-11-11 21:07:23,272 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:09:49,915 - "GET /?state=JIycQBQ3E6GWRhsp0JBgFpmVoKjChv&code=4/0AY0e-g4IR5bCHq5TAbT9zN5_E246RiB-Z6mCro477KzcW2EofkVEbPAwRcs086fVsuBdqQ&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-11 21:09:50,183 - Started server process [15089]
2020-11-11 21:09:50,184 - Waiting for application startup.
2020-11-11 21:09:50,185 - Application startup complete.
2020-11-11 21:09:50,186 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:10:04,831 - Started server process [15378]
2020-11-11 21:10:04,832 - Waiting for application startup.
2020-11-11 21:10:04,833 - Application startup complete.
2020-11-11 21:10:04,833 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:10:29,259 - Started server process [15440]
2020-11-11 21:10:29,260 - Waiting for application startup.
2020-11-11 21:10:29,261 - Application startup complete.
2020-11-11 21:10:29,262 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:10:36,214 - Started server process [15487]
2020-11-11 21:10:36,215 - Waiting for application startup.
2020-11-11 21:10:36,216 - Application startup complete.
2020-11-11 21:10:36,217 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:10:43,149 - Getting the id of folder with name folder
2020-11-11 21:11:09,292 - Getting the id of folder with name asdasd
2020-11-11 21:11:20,687 - Creating folder with name folder inside folder with id 1weIs_vptfXVN20hSIpN9thL7Vh7VgH3h
2020-11-11 21:13:09,627 - Started server process [15918]
2020-11-11 21:13:09,628 - Waiting for application startup.
2020-11-11 21:13:09,629 - Application startup complete.
2020-11-11 21:13:09,630 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:13:34,211 - Getting the id of folder with name folder
2020-11-11 21:13:35,010 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 135, in upload_to_google
    async with AIOFile(server_file_name, 'rb') as afp:
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'bin_for_temp_vids/{server_file_name}.mp4'
2020-11-11 21:16:55,703 - Started server process [16254]
2020-11-11 21:16:55,704 - Waiting for application startup.
2020-11-11 21:16:55,705 - Application startup complete.
2020-11-11 21:16:55,706 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:18:18,722 - Getting the id of folder with name folder
2020-11-11 21:18:19,567 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 135, in upload_to_google
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'bin_for_temp_vids/{server_file_name}.mp4'
2020-11-11 21:20:20,403 - Started server process [16490]
2020-11-11 21:20:20,404 - Waiting for application startup.
2020-11-11 21:20:20,406 - Application startup complete.
2020-11-11 21:20:20,407 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:20:21,138 - Getting the id of folder with name folder
2020-11-11 21:20:22,024 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 137, in upload_to_google
    async with AIOFile(server_file_name, 'rb') as afp:
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'bin_for_temp_vids/{server_file_name}.mp4'
2020-11-11 21:20:56,390 - Started server process [16573]
2020-11-11 21:20:56,391 - Waiting for application startup.
2020-11-11 21:20:56,392 - Application startup complete.
2020-11-11 21:20:56,393 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:20:58,031 - Getting the id of folder with name folder
2020-11-11 21:21:46,211 - Started server process [16675]
2020-11-11 21:21:46,212 - Waiting for application startup.
2020-11-11 21:21:46,213 - Application startup complete.
2020-11-11 21:21:46,214 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:23:05,279 - Started server process [16807]
2020-11-11 21:23:05,280 - Waiting for application startup.
2020-11-11 21:23:05,281 - Application startup complete.
2020-11-11 21:23:05,281 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:24:03,170 - Started server process [16915]
2020-11-11 21:24:03,171 - Waiting for application startup.
2020-11-11 21:24:03,172 - Application startup complete.
2020-11-11 21:24:03,176 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:24:58,949 - Started server process [16995]
2020-11-11 21:24:58,950 - Waiting for application startup.
2020-11-11 21:24:58,951 - Application startup complete.
2020-11-11 21:24:58,952 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:25:05,771 - Started server process [17038]
2020-11-11 21:25:05,772 - Waiting for application startup.
2020-11-11 21:25:05,773 - Application startup complete.
2020-11-11 21:25:05,774 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:25:41,120 - Started server process [17111]
2020-11-11 21:25:41,121 - Waiting for application startup.
2020-11-11 21:25:41,122 - Application startup complete.
2020-11-11 21:25:41,122 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:26:13,867 - Started server process [17195]
2020-11-11 21:26:13,868 - Waiting for application startup.
2020-11-11 21:26:13,868 - Application startup complete.
2020-11-11 21:26:13,869 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:26:40,436 - Started server process [17290]
2020-11-11 21:26:40,437 - Waiting for application startup.
2020-11-11 21:26:40,438 - Application startup complete.
2020-11-11 21:26:40,439 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:27:43,532 - Started server process [17432]
2020-11-11 21:27:43,533 - Waiting for application startup.
2020-11-11 21:27:43,533 - Application startup complete.
2020-11-11 21:27:43,534 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:28:07,164 - Getting the id of folder with name string
2020-11-11 21:28:07,650 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 120, in upload_to_google
    folder_id = create_folder()
TypeError: create_folder() missing 1 required positional argument: 'folder_name'
2020-11-11 21:28:35,512 - Started server process [17539]
2020-11-11 21:28:35,513 - Waiting for application startup.
2020-11-11 21:28:35,513 - Application startup complete.
2020-11-11 21:28:35,515 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:28:39,507 - Getting the id of folder with name string
2020-11-11 21:28:39,854 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 130, in upload_to_google
    async with session.post(f'{UPLOAD_API_URL}/files?uploadType=resumable',
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiohttp/client.py", line 397, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiohttp/payload.py", line 381, in __init__
    dumps(value).encode(encoding),
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
2020-11-11 21:28:56,686 - Started server process [17618]
2020-11-11 21:28:56,687 - Waiting for application startup.
2020-11-11 21:28:56,694 - Application startup complete.
2020-11-11 21:28:56,700 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:28:58,200 - Getting the id of folder with name string
2020-11-11 21:28:58,743 - Creating folder with name string inside folder with id 1weIs_vptfXVN20hSIpN9thL7Vh7VgH3h
2020-11-11 21:29:09,838 - Uploaded bin_for_temp_vids/c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65.mp4
2020-11-11 21:29:09,846 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 112, in declare_stop
    logging.info(f'Error while deleting {file_name} err: {exp}')
NameError: name 'file_name' is not defined
2020-11-11 21:29:38,006 - Started server process [17721]
2020-11-11 21:29:38,007 - Waiting for application startup.
2020-11-11 21:29:38,008 - Application startup complete.
2020-11-11 21:29:38,009 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:30:55,508 - Started server process [17913]
2020-11-11 21:30:55,509 - Waiting for application startup.
2020-11-11 21:30:55,511 - Application startup complete.
2020-11-11 21:30:55,512 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:30:57,123 - Getting the id of folder with name string
2020-11-11 21:31:06,738 - Uploaded bin_for_temp_vids/c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65.mp4
2020-11-11 21:31:06,758 - Deleted file: c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65
2020-11-11 21:31:51,178 - Getting the id of folder with name string
2020-11-11 21:31:52,003 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 136, in upload_to_google
    async with AIOFile(server_file_name, 'rb') as afp:
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'bin_for_temp_vids/c73f25ba-fd28-4b3d-9fdd-0e61cd9bce65.mp4'
2020-11-11 21:32:10,862 - Getting the id of folder with name string
2020-11-11 21:32:13,298 - Uploaded bin_for_temp_vids/55e029ca-a47d-440f-a6ba-6cae68fcd44e.mp4
2020-11-11 21:32:13,302 - Deleted file: 55e029ca-a47d-440f-a6ba-6cae68fcd44e
2020-11-11 21:34:01,214 - Started server process [18347]
2020-11-11 21:34:01,215 - Waiting for application startup.
2020-11-11 21:34:01,216 - Application startup complete.
2020-11-11 21:34:01,217 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:34:13,985 - Getting the id of folder with name string
2020-11-11 21:34:14,845 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 136, in upload_to_google
    async with AIOFile(server_file_name, 'rb') as afp:
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 180, in __aenter__
    await self.open()
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'bin_for_temp_vids/55e029ca-a47d-440f-a6ba-6cae68fcd44e.mp4'
2020-11-11 21:34:55,434 - Shutting down
2020-11-11 21:34:55,536 - Waiting for application shutdown.
2020-11-11 21:34:55,538 - Application shutdown complete.
2020-11-11 21:34:55,538 - Finished server process [18347]
2020-11-11 21:35:20,804 - Started server process [18542]
2020-11-11 21:35:20,805 - Waiting for application startup.
2020-11-11 21:35:20,806 - Application startup complete.
2020-11-11 21:35:20,807 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:35:34,793 - Getting the id of folder with name string
2020-11-11 21:35:37,481 - Uploaded bin_for_temp_vids/some_vid.mp4
2020-11-11 21:35:37,487 - Deleted file: some_vid
2020-11-11 21:37:08,371 - Getting the id of folder with name string
2020-11-11 21:39:34,527 - Started server process [19059]
2020-11-11 21:39:34,528 - Waiting for application startup.
2020-11-11 21:39:34,529 - Application startup complete.
2020-11-11 21:39:34,531 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:39:40,941 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 117, in upload_to_google
    folder_id = await get_folder_by_name(folder_name).keys()[0]
AttributeError: 'coroutine' object has no attribute 'keys'
2020-11-11 21:40:06,058 - Started server process [19159]
2020-11-11 21:40:06,059 - Waiting for application startup.
2020-11-11 21:40:06,061 - Application startup complete.
2020-11-11 21:40:06,062 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:40:08,138 - Getting the id of folder with name string
2020-11-11 21:40:08,637 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/home/sergey/Documents/python_environment/videos_NVR/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sergey/Documents/nvr/video/main.py", line 104, in declare_stop
    await upload_to_google(data_for_google.file_name,
  File "/home/sergey/Documents/nvr/video/main.py", line 118, in upload_to_google
    folder_id = folder_id.keys()[0]
TypeError: 'dict_keys' object is not subscriptable
2020-11-11 21:41:00,359 - Started server process [19314]
2020-11-11 21:41:00,366 - Waiting for application startup.
2020-11-11 21:41:00,372 - Application startup complete.
2020-11-11 21:41:00,374 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:41:17,785 - Started server process [19381]
2020-11-11 21:41:17,786 - Waiting for application startup.
2020-11-11 21:41:17,787 - Application startup complete.
2020-11-11 21:41:17,788 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:41:20,264 - Getting the id of folder with name string
2020-11-11 21:43:17,550 - Started server process [19766]
2020-11-11 21:43:17,551 - Waiting for application startup.
2020-11-11 21:43:17,552 - Application startup complete.
2020-11-11 21:43:17,553 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2020-11-11 21:43:20,902 - Getting the id of folder with name string
2020-11-11 21:43:31,488 - Uploaded bin_for_temp_vids/some_vid.mp4
2020-11-11 21:43:31,493 - Deleted file: some_vid
2020-11-12 13:49:26,403 - "GET /?state=hEPHFt4BLlRJJh3VbY2igvvwFLkkQ4&code=4/0AY0e-g5VMdp-lt07HKjGyzwnOo6q9aWrApgKhdhJuER_S1BuLk8iYS760HSzjVT8c_J1zg&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-12 13:49:26,612 - Started server process [9610]
2020-11-12 13:49:26,612 - Waiting for application startup.
2020-11-12 13:49:26,612 - Application startup complete.
2020-11-12 13:49:26,613 - Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)
2020-11-12 13:50:11,160 - Shutting down
2020-11-12 13:50:11,261 - Waiting for application shutdown.
2020-11-12 13:50:11,262 - Application shutdown complete.
2020-11-12 13:50:11,262 - Finished server process [9610]
2020-11-12 13:57:53,462 - Started server process [12741]
2020-11-12 13:57:53,463 - Waiting for application startup.
2020-11-12 13:57:53,464 - Application startup complete.
2020-11-12 13:57:53,465 - Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)
2020-11-12 13:58:08,557 - Started server process [12810]
2020-11-12 13:58:08,558 - Waiting for application startup.
2020-11-12 13:58:08,559 - Application startup complete.
2020-11-12 13:58:08,561 - Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)
2020-11-12 13:58:11,273 - Shutting down
2020-11-12 13:58:11,374 - Waiting for application shutdown.
2020-11-12 13:58:11,375 - Application shutdown complete.
2020-11-12 13:58:11,375 - Finished server process [12810]
2020-11-12 15:01:35,375 - "GET /?state=h7jEvXnCLCqQf7aH8WJZIkneksnkLD&code=4/0AY0e-g54HZsOfx8rlKr6t3AhMuatWSK_u7KYRmI6kuEfI58Otvu9fIK2dCWcBwZfdXUK6w&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-12 15:01:35,725 - Started server process [18371]
2020-11-12 15:01:35,727 - Waiting for application startup.
2020-11-12 15:01:35,729 - Application startup complete.
2020-11-12 15:01:35,732 - Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)
2020-11-12 15:02:42,337 - Was created e459b674d0c04834a39e6c0cb15fe2fc
2020-11-12 18:34:15,337 - "GET /?state=3wX5bNiwajDrSIdslMZwSNm47w0U8F&code=4/0AY0e-g5uIxxV9klgapqm-uimCWTndQbEQHBmLuRih7_dewQlhFWNbj67heyxf9dFE9nv6w&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-12 18:34:15,650 - Started server process [5082]
2020-11-12 18:34:15,650 - Waiting for application startup.
2020-11-12 18:34:15,651 - Application startup complete.
2020-11-12 18:34:15,652 - Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)
2020-11-13 10:35:13,837 - "GET /?state=2ag2N02m6dg1VzomWY7fbokfFPNTlG&code=4/0AY0e-g6rhIKIsef1hrnWuWOqCHkYGixKF93VA6jzlcwS9e557U-sow1V-Lqa8BPPsdqkDg&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
2020-11-13 10:35:14,095 - Started server process [3496]
2020-11-13 10:35:14,095 - Waiting for application startup.
2020-11-13 10:35:14,096 - Application startup complete.
2020-11-13 10:35:14,097 - Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)
2020-11-13 10:46:08,420 - File with name 123 was not found
2020-11-13 11:03:41,024 - File with name 123 was not found
2020-11-13 11:05:22,048 - Writed in the 613123fc9b3e430cbd46b0f53cf2774f
2020-11-13 11:08:31,834 - Started server process [29972]
2020-11-13 11:08:31,834 - Waiting for application startup.
2020-11-13 11:08:31,835 - Application startup complete.
2020-11-13 11:08:31,836 - Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)
2020-11-13 11:08:35,553 - Writed in the 613123fc9b3e430cbd46b0f53cf2774f
